.PHONY: clean All

All:
	@echo "----------Building project:[ Dance - Debug ]----------"
	@cd "Dance" && "$(MAKE)" -f  "Dance.mk" && "$(MAKE)" -f  "Dance.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ Dance - Debug ]----------"
	@cd "Dance" && "$(MAKE)" -f  "Dance.mk" clean
